### ISSUE TITLE
Prevent ducalis from adding duplicate comments in PR reviews

### ISSUE THREAD

**Issue by alex-kovshovik** [ignat-z/ducalis#112]
Subj.

**Comment by ignat-z** [comment]
@alex-kovshovik can't reproduce. I added test coverage for`Ducalis::Commentators::Github` class in #113 to prove that it works as featured. Feel free to reopen this issue and provide more details in case if it still happens for you

**Comment by ignat-z** [comment]
Ok, important part that it's necessary to have more than 30 comments per PR to reproduce it.

**Comment by ignat-z** [comment]
#118

**Comment by alex-kovshovik** [comment]
Ah, perfect - thanks for fixing!
