### ISSUE TITLE
Add to every # bad example at least one # good example

### ISSUE THREAD

**Issue by tmaier** [ignat-z/ducalis#91]
You describe nicely the bad cases and why to improve it. It would be great of you would show in code how you would make each case better. This increases the understanding tremendously.

**Comment by ignat-z** [comment]
@tmaier sorry for the delay, yep, you are right, it's always better to have not only bad examples. So I tried to add positive examples and write the special spec to enforce this rule for each cop. Could you please make code review: https://github.com/ignat-z/ducalis/pull/93

**Comment by ignat-z** [comment]
Done #93
