### ISSUE TITLE
Invalid hint on Ducalis/FetchExpression

### ISSUE THREAD

**Issue by mensfeld** [ignat-z/ducalis#94]
Given:

```ruby
day = params[:day] || Time.zone.today
```

Ducalis states as followed:

You can use fetch instead:

```ruby
params.fetch(:day) { Time.zone.today }
```

but it is not the same for the nil case:

```ruby
params = {}
params[:day] || Time.zone.today #=> Time.zone.today result

params = { day: nil }
params.fetch(:day) { Time.zone.today } #=> nil
```

this should not be suggested as better as the expression result is not the same and the cases may differ.

**Comment by ignat-z** [comment]
Need to rethink it, it's a little bit tricky to have `nil` as a value in a hash. Additionally, you can't have `nil` values in `ActionController::Parameters`. So, yes, it is definitely a problem but I have no specific solution for it right now.

**Comment by mensfeld** [comment]
Well it catches any variable that is a hashie like with ```params``` name, even outside of controllers scopes, so it is a problem.

**Comment by ignat-z** [comment]
I could enforce this check only on controllers, does it look like a valid solution?

**Comment by mensfeld** [comment]
it is a better one yet still it's not the same and maybe it would be good to point that out.

**Comment by ignat-z** [comment]
I added some tips how to use it and make equivalent even for edge cases like ignoring nil/false values from hash. 
#102
